//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _322_Dorogan_Mihaela
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEntities : DbContext
    {
        public DEntities()
            : base("name=DEntities")
        {
        }

        private static DEntities _context;//приватная переменная

        public static DEntities GetContext()
        {
            if (_context == null) _context = new DEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Для Category без навигационного свойства
            modelBuilder.Entity<Payment>()
                .HasRequired(p => p.Category)
                .WithMany()  // Без указания свойства
                .HasForeignKey(p => p.CategoryID)
                .WillCascadeOnDelete(false);

            // Для User с навигационным свойством
            modelBuilder.Entity<Payment>()
                .HasRequired(p => p.User)
                .WithMany(u => u.Payments)
                .HasForeignKey(p => p.UserID)
                .WillCascadeOnDelete(false);

            base.OnModelCreating(modelBuilder);
        }


        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
